---
title: "Critcal CSS energy analysis"
output: html_notebook
---

```{r}
library(ggplot2)
library(reshape)
library(e1071)
library(effsize)
library(dunn.test)
library(plyr)
library(gridExtra)
library(stringr)
library(e1071)  
library(effsize)
```

Let us first load all measures obtained from the experiment.

```{r}
# Get the measures (cpu load, memory usage, energy consumption and load time) for the specific browser (equal to folder name).
get_data <- function(browser_name) {
  subjects_path = paste("./data", browser_name, "data/nexus6p", sep="/")
  subjects <- list.dirs(subjects_path, full.names = FALSE, recursive = FALSE)
  data <- data.frame(
    name = character(),
    critical = logical(),
    energy_consumption = double(),
    time = integer(),
    memory_usage = integer(),
    cpu_usage = double(),
    stringsAsFactors = FALSE
  )

  for (subject in subjects) {
    # Obtain android measures (CPU usage)
    cpu_data <- data.frame(cpu_util = numeric())
    for (run_file in list.files(path = paste(subjects_path, subject, browser_name, "android", sep="/"), full.names = TRUE)[-1]) {
      android_results <- read.csv(run_file)
      cpu_data[nrow(cpu_data) + 1, ] <- c(mean(android_results$cpu))
    }

    # Obtain Trepn measures (time and memory usage)
    memory_data <- data.frame(mem_usage = numeric())
    time_data <- data.frame(time=numeric())
    for (run_file in list.files(path = paste(subjects_path, subject, browser_name, "trepn", sep="/"), full.names = TRUE)[-1]) {
      trepn_results <- read.csv(run_file)
      memory_data[nrow(memory_data) + 1, ] <- c(mean(trepn_results[, 2]))
      time_data[nrow(time_data) + 1, ] <- c(max(trepn_results[, 1]))
    }
    
    # Obtain Batterystats measures (energy consumption)
    energy_data <- data.frame(energy = numeric())
    for (run_file in list.files(path = paste(subjects_path, subject, browser_name, "batterystats", sep="/"), full.names = TRUE, pattern = "^Joule")) {
      batterystats_results <- read.csv(run_file)
      energy_data[nrow(energy_data) + 1, ] <- c(mean(batterystats_results[1, ]))
    }
    
    run_data <- data.frame(
      rep(strsplit(subject, "-")[[1]][2], nrow(energy_data)),
      rep(startsWith(subject, "subjects_critical"), nrow(energy_data)),
      energy_data,
      time_data,
      memory_data,
      cpu_data
    )
    names(run_data) <- names(data)
    data <- rbind(data, run_data)
  }

  return(data)
}

firefox_data <- get_data("firefox")
chrome_data <- get_data("chrome")
```

Next, let us define a function to plot two histograms of values for non-critical and critical categories, as well as their qq plots.

```{r}
plot_hist_qq <- function(data, column, metric_label, unit_label, browser_name) {
  # Plot histogram
  hist_plot <- ggplot(chrome_data, aes_string(x = column, fill = 'critical', color = 'critical')) + geom_histogram(position = 'identity', alpha = 0.5) + xlab(paste(metric_label, ' (', unit_label, ')', sep='')) + ylab('Frequency') + ggtitle(paste('Histogram of ', metric_label, ' (', browser_name, ')', sep=''))+ scale_color_manual(labels=c('Original', 'Critical'), values=c('red', 'blue')) + scale_fill_manual(labels=c('Original', 'Critical'), values=c('red', 'blue')) + theme_minimal() +
    theme(plot.title = element_text(hjust = 0.5),
          axis.text.y   = element_text(size=14),
          axis.text.x   = element_text(size=14),
          axis.title.y  = element_text(size=14),
          axis.title.x  = element_text(size=14),
          panel.background = element_blank(),
          legend.position = c(0.9, 0.9),
          legend.title=element_blank(),
          axis.line = element_line(colour = "black"))

  # Plot qq
  qq_plot <- ggplot(chrome_data, aes_string(sample = column, fill = 'critical', color = 'critical')) + stat_qq(alpha = 0.5) +  stat_qq_line() + xlab('Theoretical Quantile') + ylab('Actual Quantile') + ggtitle(paste('Q-Q Plot of ', metric_label, ' (', browser_name, ')', sep='')) + scale_color_manual(labels=c('Original', 'Critical'), values=c('red', 'blue')) + scale_fill_manual(labels=c('Original', 'Critical'), values=c('red', 'blue')) + theme_minimal() +
    theme(plot.title = element_text(hjust = 0.5),
          axis.text.y   = element_text(size=14),
          axis.text.x   = element_text(size=14),
          axis.title.y  = element_text(size=14),
          axis.title.x  = element_text(size=14),
          panel.background = element_blank(),
          legend.position = c(0.1, 0.9),
          legend.title=element_blank(),
          axis.line = element_line(colour = "black"))
  
  show(hist_plot)
  show(qq_plot)
}

plot_hist_qq(chrome_data, 'energy_consumption', "Energy Consumption", "Joules", 'Chrome')
plot_hist_qq(chrome_data, 'time', "Initial Load Time", "Milliseconds", 'Chrome')
plot_hist_qq(chrome_data, 'cpu_usage', "CPU Utilisation", "%", 'Chrome')
plot_hist_qq(chrome_data, 'memory_usage', "Memory Utilisation", "kB", 'Chrome')

plot_hist_qq(firefox_data, 'energy_consumption', "Energy Consumption", "Joules", 'Firefox')
plot_hist_qq(firefox_data, 'time', "Initial Load Time", "Milliseconds", 'Firefox')
plot_hist_qq(firefox_data, 'cpu_usage', "CPU Utilisation", "%", 'Firefox')
plot_hist_qq(firefox_data, 'memory_usage', "Memory Utilisation", "kB", 'Firefox')
```

# RQ1

```{r}
#perform shapiro tests to check for normality. p-values lower than 0.05 are not normally distributed
print(firefox_data)
shapiro.test(firefox_data[firefox_data$critical == TRUE,]$energy_consumption)
shapiro.test(firefox_data[firefox_data$critical == TRUE,]$time)
shapiro.test(firefox_data[firefox_data$critical == TRUE,]$memory_usage)
shapiro.test(firefox_data[firefox_data$critical == TRUE,]$cpu_usage)
```

```{r}
#perform wilcox test as the data is not normally distributed (at least not before applying transformations or removing outliers)
wilcox.test(firefox_data[firefox_data$critical == TRUE,]$energy_consumption, firefox_data[firefox_data$critical == FALSE,]$energy_consumption)
```

```{r}
print(chrome_data)
#perform shapiro tests to check for normality. p-values lower than 0.05 are not normally distributed
shapiro.test(chrome_data$energy_consumption)
shapiro.test(chrome_data$time)
shapiro.test(chrome_data$memory_usage)
shapiro.test(chrome_data$cpu_usage)
```

```{r}

#perform wilcox test as the data is not normally distributed (at least not before applying transformations or removing outliers)
wilcox.test(chrome_data[chrome_data$critical == TRUE,]$energy_consumption, chrome_data[chrome_data$critical == FALSE,]$energy_consumption, mu = 0)
```

