'use strict';(function(){(function(){var cmpScriptElement=document.createElement('script');var firstScript=document.getElementsByTagName('script')[0];cmpScriptElement.async=true;cmpScriptElement.type='text/javascript';var cmpVersion='https://quantcast.mgr.consensu.org/tcfv2/cmp2.js';cmpScriptElement.src=cmpVersion;window._qevents=window._qevents||[];(function(){var elem=document.createElement('script');elem.src=(document.location.protocol=="https:"?"https://secure":"http://edge")+".quantserve.com/quant.js";elem.async=true;elem.type="text/javascript";var scpt=document.getElementsByTagName('script')[0];scpt.parentNode.insertBefore(elem,scpt);})();var qcaccount='p-'+'u8c9pru4NG2Ps';window._qevents.push({qacct:qcaccount,source:"choice"});var cmpNoScriptElement=document.createElement('noscript');var div=document.createElement('div');div.style.display="none;";var img=document.createElement('img');img.src='//pixel.quantserve.com/pixel/p-'+'u8c9pru4NG2Ps'+'.gif';img.border='0';img.height='1';img.width='1';img.alt='Quantcast';div.appendChild(img);cmpNoScriptElement.appendChild(div);firstScript.parentNode.insertBefore(cmpNoScriptElement,firstScript);firstScript.parentNode.insertBefore(cmpScriptElement,firstScript);})();(function(){var css=""
+" .qc-cmp-button { "
+"   background-color: #007F0E !important; "
+"   border-color: #007F0E !important; "
+" } "
+" .qc-cmp-button:hover { "
+"   border-color: #007F0E !important; "
+" } "
+" .qc-cmp-alt-action, "
+" .qc-cmp-link { "
+"   color: #007F0E !important; "
+" } "
+" .qc-cmp-button.qc-cmp-secondary-button:hover { "
+"   background-color: #007F0E !important; "
+"   border-color: #007F0E !important; "
+" } "
+" .qc-cmp-button.qc-cmp-secondary-button:hover { "
+"   color: #ffffff !important; "
+" } "
+" .qc-cmp-button.qc-cmp-secondary-button { "
+"   color: #888 !important; "
+" } "
+" .qc-cmp-button.qc-cmp-secondary-button { "
+"   background-color: #eee !important; "
+"   border-color: transparent !important; "
+" } "
+" .qc-cmp-ui a, "
+" .qc-cmp-ui .qc-cmp-alt-action { "
+"   color: #888 !important; "
+" } "
+" .qc-cmp-small-toggle.qc-cmp-toggle-on, "
+" .qc-cmp-toggle.qc-cmp-toggle-on { "
+"   background-color: #888!important; "
+"   border-color: #888!important; "
+" } "
+"#qc-cmp2-ui{height: fit-content;max-height:100vh!important;}#qc-cmp2-ui .qc-cmp2-summary-section .qc-cmp2-summary-info{max-height: 22vh!important;}#qc-cmp2-ui .qc-cmp2-summary-section img {height: 40px!important;;width: auto!important;}#qc-cmp2-ui .qc-cmp2-consent-info h2{font-size:1em!important;}#qc-cmp2-ui .qc-cmp2-consent-info p{line-height:1.3em!important;}#qc-cmp2-ui .qc-cmp2-footer, #qc-cmp2-ui .qc-cmp2-summary-buttons{flex-direction: row-reverse!important;}#qc-cmp2-ui .qc-cmp2-footer button{width: 48%!important; margin:0!important; height:50px;}#qc-cmp2-ui .qc-cmp2-list-item .qc-cmp2-list-item-title{line-height: 1.1em!important;}#qc-cmp2-ui .qc-cmp2-scrollable-section{max-height: 31vh!important;}"
+""
+"";var stylesElement=document.createElement('style');var re=new RegExp('&quote;','g');css=css.replace(re,'"');stylesElement.type='text/css';if(stylesElement.styleSheet){stylesElement.styleSheet.cssText=css;}else{stylesElement.appendChild(document.createTextNode(css));}
var head=document.head||document.getElementsByTagName('head')[0];head.appendChild(stylesElement);})();var autoDetectedLanguage='en';function splitLang(lang){return lang.length>2?lang.split('-')[0]:lang;};function isSupported(lang){var langs=['en','fr','de','it','es','da','nl','el','hu','pt','ro','fi','pl','sk','sv','no','ru','bg','ca','cs','et','hr','lt','lv','mt','sl','tr','zh'];return langs.indexOf(lang)===-1?false:true;};if(isSupported(splitLang(document.documentElement.lang))){autoDetectedLanguage=splitLang(document.documentElement.lang);}else if(isSupported(splitLang(navigator.language))){autoDetectedLanguage=splitLang(navigator.language);};var choiceMilliSeconds=(new Date).getTime();window.__tcfapi('init',2,function(){},{'premiumProperties':{},'coreUiLabels':{},'premiumUiLabels':{},'theme':{'uxPrimaryButtonColor':'#007F0E','uxSecondaryButtonTextColor':'#888','uxToogleActiveColor':'#888','uxLinkColor':'#888',},'coreConfig':{'initScreenBodyTextOption':1,'consentScope':'service','lang_':autoDetectedLanguage,'defaultToggleValue':'off','displayUi':'always','displayPersistentConsentLink':false,'initScreenRejectButtonShowing':false,'publisherLogo':'https://scripts.publy.net/publy_logo.svg','publisherPurposeIds':[1,2,3,4,5,6,7,8,9,10],'publisherPurposeLegitimateInterestIds':[],'publisherSpecialPurposesIds':[],'publisherFeaturesIds':[],'publisherSpecialFeaturesIds':[1,2],'stacks':[],'softOptInEnabled':false,'uiLayout':'popup','vendorListUpdateFreq':30,'thirdPartyStorageType':'iframe','showSummaryView':true,'persistentConsentLinkLocation':3,'quantcastAccountId':'u8c9pru4NG2Ps','privacyMode':["GDPR","USP"],'hashCode':'+jKsFYx+6gxE4FYtAada6Q','publisherCountryCode':'IT','publisherName':'NewSicilia','vendorPurposeIds':[1,2,3,4,5,6,7,8,9,10],'vendorFeaturesIds':[1,2,3],'vendorPurposeLegitimateInterestIds':[2,3,4,5,6,7,8,9,10],'vendorSpecialFeaturesIds':[1,2],'vendorSpecialPurposesIds':[1,2],'googleEnabled':true,'uspVersion':1,'uspJurisdiction':["US"],'uspLspact':'N','suppressCcpaLinks':true,}});})();